### ISSUE TITLE
Documentation: confused about importc, static statements

### ISSUE THREAD

**Issue by mavavilj** [PMunch/futhark#16]
Documentation: confused about importc, static statements in:

https://github.com/PMunch/futhark

As a nim newbie I don't understand these parts.

**Comment by PMunch** [comment]
Anything particular you're confused about? You just linked to the entire repository..

**Comment by mavavilj** [comment]
Well I had to search for:

importc
https://github.com/PMunch/futhark/blob/875a7f5cf727483bc4c4d394f7d3c23699002aa8/src/futhark.nim#L380

and

static macro seems to mean "run these at compile time"

**Comment by PMunch** [comment]
Oh right. Yes `importc` is a macro defined by Futhark which is what generates Nim code based on the header files you want to import. `static` is just a Nim thing that runs code on compile-time, in this case I just use it to write a small C file to link against so that we can statically compile stb instead of having to build a DLL/so out of it.

**Comment by crystalthoughts** [comment]
It would be great to have a more detailed explainer on these parts in the readme - I'm also having to  dig into it a bit more than I expected.
For example, why do you need to repeat 
```
"""
  #define STB_IMAGE_IMPLEMENTATION
  #include "./lib/c/stb_image.h"
  """
```
in both static and importc (in different forms). More explanation about dlls would also be great.
