### ISSUE TITLE
Why capital letter proc? Why varargs?

### ISSUE THREAD

**Issue by arkanoid87** [PMunch/futhark#54]
line in C header
```C
CLIENT_NET_API DWORD CALL_METHOD CLIENT_GetSDKVersion();
```

after preprocessing
```C
unsigned int CLIENT_GetSDKVersion();
```

after futhark pass
```nim
when not declared(Clientgetsdkversion):
  proc Clientgetsdkversion*(): cuint {.cdecl, varargs,
                                       importc: "CLIENT_GetSDKVersion".}
else:
  static :
    hint("Declaration of " & "CLIENT_GetSDKVersion" &
        " already exists, not redeclaring")
```

generated C code by nim compiler
```C
...
N_CDECL(unsigned int, CLIENT_GetSDKVersion)(...);
...
```

error
```
error: ISO C requires a named argument before ‘...’
```

removing `varargs` from pragma fixes the problem

**Comment by PMunch** [comment]
The capital letter is simply because the original C procedure starts with a capital letter. Futhark tries to maintain the best compatibility with the original, and thus also tutorials and such. Because of the case and underscore insensitivity of Nim that identifier can also be written as `CLIENT_GetSDKVersion`, same as the C version.

The varargs praga is simply added because Clang tells us the procedure is variadic: https://github.com/PMunch/futhark/blob/master/src/opir.nim#L117 and has already been reported here https://github.com/PMunch/futhark/issues/44. Why clang does this is still not known, which version of Clang are you using?

**Comment by PMunch** [comment]
The idea is that you shouldn't have to edit the Futhark file. Because of all the `when declared` guards it should suffice to simply declare your procs before `importc`. This isn't always feasible however due to how tangled types and procedures can get. Another option would be to add a `opirOutputHook` or similar, this would allow you to change the data fed into Futhark in a very structured way.
